use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
keep-going: "{{cookiecutter.keep_going}}"
restart-times: "{{cookiecutter.restart_times}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"
{%- if cookiecutter.directory != "" %}
directory: "{{cookiecutter.directory}}"
{%- endif %}
latency-wait: "{{cookiecutter.latency_wait}}"
jobs: "{{cookiecutter.jobs}}"
cluster: "qsub-submit.py"
cluster-status: "qsub-status.py"
jobscript: "qsub-jobscript.sh"
local-cores: 1
