{%- if cookiecutter.directory != "" %}
directory: "{{cookiecutter.directory}}"
{%- endif %}
{%- if cookiecutter.conda_prefix != "" %}
conda-prefix: "{{cookiecutter.conda_prefix}}"
{%- endif %}
restart-times: "{{cookiecutter.restart_times}}"
use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
keep-going: "{{cookiecutter.keep_going}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"
latency-wait: "{{cookiecutter.latency_wait}}"
jobs: "{{cookiecutter.jobs}}"
cluster: "qsub_submit.py"
cluster-status: "qsub_status.py"
jobscript: "qsub-jobscript.sh"
local-cores: 1
